version: '3.8'

services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - ./../src:/app/src
      - ./../public:/app/public
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./entrypoint.sh:/usr/local/bin/entrypoint.sh
      - ./../index.html:/app/index.html
      - ./../package.json:/app/package.json
      - ./../vite.config.ts:/app/vite.config.ts
    env_file:
      - ../.env
    environment:
      - NODE_ENV=development
      - VITE_ENVIRONMENT=development
      - PORT=5173
    restart: unless-stopped
